[project]
name = "techbit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "moviepy>=2.2.1",
    "ollama>=0.5.1",
    "requests>=2.32.4",
]
